<link rel="stylesheet" href="notebooks/styles.css">

<div class="title-wrap">
  <h1 class="title-main" style="font-weight: bold; font-size: 2.65rem; margin-bottom: 0.5rem;">
  Spatial Data Science Approaches to Wildfire Severity Modeling
</h1>
<h2 class="title-sub" style="font-style: italic; font-size: 1.8rem; margin-top: 0rem; margin-bottom: 0.2rem;">
  A GIS‑Driven, Tree‑Based Machine Learning Analysis of California Wildfires
</h2>
</div>

# Module 8B: *Fire Ignition Feature Ablation*
##### Version Number: 4.0
---
### Contents  
> *Build Models*\
> *SHAP*\
> *Set Ablation*
---
### Notes
---
### Inputs
---
### Outputs 
---
### User Defined Dependencies

In [1]:
import os
import sys

# Allow import of custom modules from the parent directory
sys.path.append(os.path.abspath(os.path.join('..')))

from src.data_utils import *
from src.model_utils import *
from src.plot_utils import *

---
### Third Party Dependencies

In [2]:
# Core libraries
import pandas as pd
import numpy as np
import json

# Modeling libraries
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.model_selection import train_test_split

---

###  Load Data

In [3]:
X_ignition = pd.read_csv('../data/processed/X_ignition.csv')
y_ignition = pd.read_csv('../data/processed/y_ignition.csv').squeeze()  # Load as Series      
details_ignition = pd.read_csv('../data/processed/details_ignition.csv')

pal_details = pd.read_csv('../data/processed/pal_details.csv')
pal_X = pd.read_csv('../data/processed/pal_X.csv')
pal_y = pd.read_csv('../data/processed/pal_y.csv')

best_strategy = pd.read_csv('../data/processed/ignition_best_strategy.csv')

with open('model_parameters_ignition.json', 'r') as f:
    model_parameters = json.load(f)

with open('feature_sets.json', 'r') as f:
    feature_sets = json.load(f)

## Subset

In [4]:
reform = pd.concat([X_ignition,y_ignition], axis=1)
subset = subset_df(reform, 'Target_Ignition_Lag', 500)

y = subset['Target_Ignition_Lag']
X = subset.drop(columns='Target_Ignition_Lag')

In [5]:
X_rf, y_rf = apply_balancing('RF', best_strategy, X, y)
X_xgb, y_xgb = apply_balancing('XGB', best_strategy, X, y)

## Build Models

In [6]:
RF_parameters = model_parameters['Random Forest']
XGB_parameters = model_parameters['XGBoost']

# Build tuned models
ignition_xbg = xgb.XGBClassifier(**XGB_parameters)
ignition_rf = RandomForestClassifier(**RF_parameters)

display(RF_parameters)
display(XGB_parameters)

{'n_estimators': 50,
 'max_depth': 10,
 'min_samples_split': 5,
 'max_features': 'log2',
 'class_weight': 'balanced'}

{'objective': 'multi:softmax',
 'num_class': 3,
 'n_estimators': 150,
 'max_depth': 5,
 'learning_rate': 0.1,
 'verbosity': 0}

In [7]:
models = {
    "XGB": ignition_xbg, 
    "RF": ignition_rf
}

## SHAP

### XGB Ignition SHAP

In [8]:
xgb_top_10 = get_shap(ignition_xbg, X_xgb, y_xgb)
xgb_top_10

 20%|====                | 511/2500 [00:11<00:42]

 23%|=====               | 565/2500 [00:12<00:41]

 25%|=====               | 622/2500 [00:13<00:39]

 27%|=====               | 681/2500 [00:14<00:37]

 30%|======              | 739/2500 [00:15<00:35]

 32%|======              | 798/2500 [00:16<00:34]

 34%|=======             | 857/2500 [00:17<00:32]

 37%|=======             | 917/2500 [00:18<00:31]

 39%|========            | 976/2500 [00:19<00:29]

 41%|========            | 1034/2500 [00:20<00:28]

 44%|=========           | 1092/2500 [00:21<00:27]

 46%|=========           | 1151/2500 [00:22<00:25]

 48%|==========          | 1209/2500 [00:23<00:24]

 51%|==========          | 1268/2500 [00:24<00:23]

 53%|===========         | 1328/2500 [00:25<00:22]

 55%|===========         | 1379/2500 [00:26<00:21]

 57%|===========         | 1425/2500 [00:27<00:20]

 59%|============        | 1479/2500 [00:28<00:19]

 62%|============        | 1538/2500 [00:29<00:18]

 64%|=============       | 1596/2500 [00:30<00:16]

 66%|=============       | 1656/2500 [00:31<00:15]

 69%|==============      | 1715/2500 [00:32<00:14]

 71%|==============      | 1774/2500 [00:33<00:13]

 73%|===============     | 1833/2500 [00:34<00:12]

 76%|===============     | 1893/2500 [00:35<00:11]

 78%|================    | 1952/2500 [00:36<00:10]

 80%|================    | 2010/2500 [00:37<00:09]

 83%|=================   | 2071/2500 [00:38<00:07]

 85%|=================   | 2129/2500 [00:39<00:06]

 88%|==================  | 2188/2500 [00:40<00:05]

 90%|==================  | 2248/2500 [00:41<00:04]

 92%|==================  | 2303/2500 [00:42<00:03]

 94%|=================== | 2353/2500 [00:43<00:02]

 96%|=================== | 2407/2500 [00:44<00:01]

 99%|===================| 2466/2500 [00:45<00:00]

                                         0         1
0                        developed_percent  0.483098
1                       population_density  0.425507
2                            total_housing  0.312309
3                Solar Radiation 7 Day Avg  0.285942
4                            intermix_zone  0.228234
5                     NDVI_mean_difference  0.205906
6                           interface_zone  0.195931
7  Daily Maximum Air Temperature 7 Day Avg  0.178608
8            Palmer Drought Severity Index  0.166239
9                              SPI 180-Day  0.156734

### RF Ignition SHAP

In [9]:
rf_top_10 = get_shap(ignition_rf, X_rf, y_rf)
rf_top_10

 62%|============        | 1556/2500 [00:11<00:06]

 68%|==============      | 1709/2500 [00:12<00:05]

 74%|===============     | 1847/2500 [00:13<00:04]

 79%|================    | 1975/2500 [00:14<00:03]

 85%|=================   | 2120/2500 [00:15<00:02]

 91%|==================  | 2271/2500 [00:16<00:01]

 97%|=================== | 2426/2500 [00:17<00:00]

                                                0         1
0                               developed_percent  0.021244
1                                   total_housing  0.017884
2                                  influence_zone  0.015622
3                              population_density  0.015376
4                                   median_income  0.013433
5                                total_population  0.013127
6                                 housing_density  0.013097
7                                  northness_mean  0.011672
8  northness_mean_x_Daily Maximum Air Temperature  0.010303
9                                   intermix_zone  0.009463

## Set Ablation

In [10]:
for set_name, columns in feature_sets.items():
    print(f"{set_name}: {columns}")
    print("\n")

Water Demand: ['Actual Evapotranspiration', 'Solar Radiation', 'Solar Radiation 7 Day Avg', 'Daily Minimum Air Temperature', 'Daily Maximum Air Temperature', 'Daily Maximum Air Temperature 7 Day Avg', 'Daily Minimum Air Temperature 7 Day Avg', 'Vapor Pressure Deficit', 'Vapor Pressure Deficit 7 Day Avg', 'Wind Speed', 'Wind Speed 7 Day Avg']


Water Supply: ['Precipitation', 'Precipitation 7 Day Avg', 'Maximum Relative Humidity', 'Minimum Relative Humidity', 'Maximum Relative Humidity 7 Day Avg', 'Minimum Relative Humidity 7 Day Avg', 'Specific Humidity', '100-hour Dead Fuel Moisture', '1000-hour Dead Fuel Moisture']


Water Supply Indexes: ['SPI 30-Day', 'SPI 180-Day', 'SPEI 30-Day', 'SPEI 90-Day', 'SPEI 180-Day', 'Palmer Drought Severity Index']


Fire Danger: ['Burning Index', 'Energy Release Component', 'Santa_Ana_Score']


Social: ['total_housing', 'total_population', 'housing_density', 'population_density', 'median_income']


Infrastructure: ['power_line_meters', 'power_line_density', 'road_length_meters', 'road_density']


Elevation: ['elevation_range', 'elevation_mean', 'elevation_std', 'slope_max', 'slope_range', 'slope_mean', 'slope_std', 'northness_mean', 'eastness_mean']


WUI: ['influence_zone', 'interface_zone', 'intermix_zone']


Ecoregion: ['dominant_province_percent', 'sum_province_area', 'sum_section_area', 'dominant_section_percent']


Land Cover: ['forest_percent', 'developed_percent', 'other_percent', 'shrub_grass_percent', 'wetlands_percent']


Interactions: ['Wind Speed_x_100-hour Dead Fuel Moisture', 'Vapor Pressure Deficit_x_Solar Radiation', 'Precipitation_x_1000-hour Dead Fuel Moisture', 'northness_mean_x_Daily Maximum Air Temperature', 'road_density_x_forest_percent', 'power_line_density_x_total_housing']


Wind Slope: ['Wind Speed_x_slope_mean', 'Wind Speed_x_slope_max', 'Wind Speed_x_northness_mean', 'Wind Speed_x_eastness_mean', 'Wind Speed_x_elevation_mean', 'Wind Speed_x_elevation_range', 'Wind Speed 7 Day Avg_x_slope_mean', 'Wind Speed 7 Day Avg_x_slope_max', 'Wind Speed 7 Day Avg_x_northness_mean', 'Wind Speed 7 Day Avg_x_eastness_mean', 'Wind Speed 7 Day Avg_x_elevation_mean', 'Wind Speed 7 Day Avg_x_elevation_range']


Others: ['NDVI_mean_difference', 'NDVI_mean_difference_has_value', 'reservoir_count', 'total_reservoir_level', 'stations_missing_levels']


Coded Ecoregions: ['dominant_province_description_American Semi-Desert and Desert', 'dominant_province_description_California Coastal Chaparral Forest and Shrub', 'dominant_province_description_California Coastal Range Open Woodland-Shrub-Coniferous Forest-Meadow', 'dominant_province_description_California Coastal Steppe-Mixed Forest-Redwood Forest', 'dominant_province_description_California Dry Steppe', 'dominant_province_description_Intermountain Semi-Desert', 'dominant_province_description_Intermountain Semi-Desert and Desert', 'dominant_province_description_Sierran Steppe-Mixed Forest-Coniferous Forest-Alpine Meadow', 'dominant_section_description_Central California Coast', 'dominant_section_description_Central Valley Coast Ranges', 'dominant_section_description_Colorado Desert', 'dominant_section_description_Great Valley', 'dominant_section_description_Klamath Mountains', 'dominant_section_description_Modoc Plateau', 'dominant_section_description_Mojave Desert', 'dominant_section_description_Mono', 'dominant_section_description_Northern California Coast', 'dominant_section_description_Northern California Coast Ranges', 'dominant_section_description_Northern California Interior Coast Ranges', 'dominant_section_description_Northwestern Basin and Range', 'dominant_section_description_Sierra Nevada', 'dominant_section_description_Sierra Nevada Foothills', 'dominant_section_description_Sonoran Desert', 'dominant_section_description_Southeastern Great Basin', 'dominant_section_description_Southern California Coast', 'dominant_section_description_Southern California Mountains and Valleys', 'dominant_section_description_Southern Cascades']


Coded Seasons: ['Season_Spring', 'Season_Summer', 'Season_Fall', 'Season_Winter']

In [11]:
compare = []

compare.append(compare_model(ignition_xbg, X, y, best_strategy,
                                     name = 'XGB', test_set = 'Full'))

compare.append(compare_model(ignition_rf, X, y, best_strategy,
                                     name = 'RF', test_set = 'Full'))

for set_name, set_list in feature_sets.items():
    for model_name, model in models.items():
        print("Testing " + f"{model_name}: {set_name}")
        X_section = X.drop(columns = set_list)
        compare.append(compare_model(model, X_section, y, best_strategy,
                                     name = model_name, test_set = set_name))

Testing XGB: Water Demand

Testing RF: Water Demand

Testing XGB: Water Supply

Testing RF: Water Supply

Testing XGB: Water Supply Indexes

Testing RF: Water Supply Indexes

Testing XGB: Fire Danger

Testing RF: Fire Danger

Testing XGB: Social

Testing RF: Social

Testing XGB: Infrastructure

Testing RF: Infrastructure

Testing XGB: Elevation

Testing RF: Elevation

Testing XGB: WUI

Testing RF: WUI

Testing XGB: Ecoregion

Testing RF: Ecoregion

Testing XGB: Land Cover

Testing RF: Land Cover

Testing XGB: Interactions

Testing RF: Interactions

Testing XGB: Wind Slope

Testing RF: Wind Slope

Testing XGB: Others

Testing RF: Others

Testing XGB: Coded Ecoregions

Testing RF: Coded Ecoregions

Testing XGB: Coded Seasons

Testing RF: Coded Seasons

In [12]:
comparisons = pd.DataFrame(compare)

In [13]:
XGB = comparisons[comparisons['Model'] == 'XGB'] 
RF = comparisons[comparisons['Model'] == 'RF']

In [14]:
full_XGB = XGB.loc[XGB['Test Set']=='Full','Macro F1'].values[0]
full_RF = RF.loc[RF['Test Set']=='Full','Macro F1'].values[0]

In [15]:
XGB['Macro F1 Percent Difference'] = ((full_XGB - XGB['Macro F1']) / full_XGB) * 100
RF['Macro F1 Percent Difference'] = ((full_RF - RF['Macro F1']) / full_RF) * 100

C:\Users\dusti\AppData\Local\Temp\ipykernel_10796\2524239291.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  XGB['Macro F1 Percent Difference'] = ((full_XGB - XGB['Macro F1']) / full_XGB) * 100
C:\Users\dusti\AppData\Local\Temp\ipykernel_10796\2524239291.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RF['Macro F1 Percent Difference'] = ((full_RF - RF['Macro F1']) / full_RF) * 100

In [16]:
RF

,Test Set,Model,Weighted F1,Macro F1,High Risk Recall,Macro F1 Percent Difference
1,Full,RF,0.467405,0.444616,0.322917,0.000000
3,Water Demand,RF,0.453488,0.432453,0.333333,2.735623
5,Water Supply,RF,0.474357,0.451992,0.364583,-1.659043
7,Water Supply Indexes,RF,0.473375,0.451224,0.333333,-1.486176
9,Fire Danger,RF,0.470498,0.448394,0.354167,-0.849706
11,Social,RF,0.462680,0.441434,0.322917,0.715625
13,Infrastructure,RF,0.473933,0.451201,0.395833,-1.481058
15,Elevation,RF,0.462023,0.439915,0.322917,1.057410
17,WUI,RF,0.476212,0.453914,0.343750,-2.091371
19,Ecoregion,RF,0.465443,0.443156,0.354167,0.328382
21,Land Cover,RF,0.481970,0.460765,0.354167,-3.632137
23,Interactions,RF,0.491038,0.467093,0.354167,-5.055445
25,Wind Slope,RF,0.473541,0.450878,0.333333,-1.408486
27,Others,RF,0.484233,0.462368,0.354167,-3.992781
29,Coded Ecoregions,RF,0.488973,0.466071,0.343750,-4.825537
31,Coded Seasons,RF,0.463084,0.441651,0.312500,0.666949

In [17]:
XGB

,Test Set,Model,Weighted F1,Macro F1,High Risk Recall,Macro F1 Percent Difference
0,Full,XGB,0.446622,0.424865,0.260417,0.000000
2,Water Demand,XGB,0.444739,0.422260,0.239583,0.612982
4,Water Supply,XGB,0.453244,0.430424,0.291667,-1.308442
6,Water Supply Indexes,XGB,0.457268,0.435989,0.260417,-2.618240
8,Fire Danger,XGB,0.432756,0.411073,0.281250,3.246138
10,Social,XGB,0.438063,0.416048,0.250000,2.075128
12,Infrastructure,XGB,0.438173,0.415979,0.260417,2.091445
14,Elevation,XGB,0.452095,0.429484,0.281250,-1.087263
16,WUI,XGB,0.465917,0.446185,0.322917,-5.018157
18,Ecoregion,XGB,0.446386,0.425649,0.250000,-0.184631
20,Land Cover,XGB,0.450247,0.429081,0.260417,-0.992268
22,Interactions,XGB,0.435750,0.414826,0.229167,2.362687
24,Wind Slope,XGB,0.446183,0.426287,0.250000,-0.334858
26,Others,XGB,0.451077,0.430623,0.260417,-1.355322
28,Coded Ecoregions,XGB,0.437619,0.415655,0.250000,2.167668
30,Coded Seasons,XGB,0.440025,0.417280,0.270833,1.785244