# Mapping the Potential Destructive Power of Wildfires Using Machine Learning

## Appendix B: *Gridmet Combination*
- *Version Number: 4.0*
---
### Contents  
> 1. *Combine Datsets* 
> 2. *Visualization*
---
### Notes
---
### Inputs
> - **gridMET**: <https://www.climatologylab.org/gridmet.html
    - extracted CSV = '../data/raw/gridmet_point_extraction.csv'
---
### Outputs  
- `gridmet_final.csv` - cleaned dataset of environmental variables
- `weather_meta` - column names, descriptions, and units for future reference
---
### User Created Dependencies  
---

### Third Party Dependencies  
---

In [1]:
import pandas as pd

### Load all gridMET datasets

In [2]:
weather = pd.read_csv('../data/raw/gridmet_point_extraction.csv')
spi180d_data = pd.read_csv('../data/raw/spi180d_extraction.csv')
spi30d_data = pd.read_csv('../data/raw/spi30d_extraction.csv')
spei30d_data = pd.read_csv('../data/raw/spei30d_extraction.csv')
spei90d_data = pd.read_csv('../data/raw/spei90d_extraction.csv')
spei180d_data = pd.read_csv('../data/raw/spei180d_extraction.csv')
pdsi_data = pd.read_csv('../data/raw/pdsi_extraction.csv')
names = pd.read_csv('../data/raw/gridmet_variables.csv')

In [3]:
weather

,Sample_ID,Date,bi,erc,etr,fm100,fm1000,pr,rmax,rmin,sph,srad,tmmn,tmmx,vpd,vs
0,1,2018-01-01,24.0,37.0,1.7,16.600000,13.700000,0.0,97.800003,52.700001,0.00738,145.600006,283.000000,290.700012,0.41,1.3
1,1,2018-01-02,25.0,39.0,2.0,15.900000,13.800000,0.0,90.599998,43.200001,0.00792,132.199997,285.299988,294.399994,0.68,1.2
2,1,2018-01-03,23.0,36.0,1.6,15.900000,13.800000,0.0,93.500000,53.400002,0.00857,69.900002,286.000000,292.899994,0.50,1.2
3,1,2018-01-04,27.0,38.0,2.3,16.299999,14.100000,0.0,98.300003,47.700001,0.00847,151.199997,285.000000,294.200012,0.56,1.9
4,1,2018-01-05,31.0,38.0,3.1,16.000000,14.200000,0.0,89.699997,46.299999,0.00848,151.600006,286.500000,294.600006,0.67,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446335,173,2025-01-19,23.0,28.0,1.7,12.600000,20.700001,0.0,76.199997,28.600000,0.00171,121.400002,262.899994,276.799988,0.31,2.7
446336,173,2025-01-20,26.0,29.0,1.8,12.600000,20.200001,0.0,77.000000,26.700001,0.00143,125.599998,260.500000,275.200012,0.28,3.3
446337,173,2025-01-21,27.0,32.0,2.4,11.300000,19.700001,0.0,53.599998,20.200001,0.00144,124.400002,265.500000,279.000000,0.45,3.0
446338,173,2025-01-22,26.0,34.0,2.3,10.300000,19.299999,0.0,51.900002,18.799999,0.00148,126.099998,266.299988,280.399994,0.50,2.5
446339,173,2025-01-23,30.0,37.0,3.1,9.100000,18.799999,0.0,39.799999,14.400000,0.00131,126.000000,268.500000,282.200012,0.62,3.0

## 1. Combine datasets

#### Rename index columns so they are unique

In [4]:
spi180d_data.rename(columns={'spi': 'spi180d'}, inplace=True)
spi30d_data.rename(columns={'spi': 'spi30d'}, inplace=True)
spei30d_data.rename(columns={'spei': 'spei30d'}, inplace=True)
spei90d_data.rename(columns={'spei': 'spei90d'}, inplace=True)
spei180d_data.rename(columns={'spei': 'spei180d'}, inplace=True)

#### Attach data to main datset

In [5]:
weather['spi30d'] = spi30d_data['spi30d']
weather['spi180d'] = spi180d_data['spi180d']
weather['spei30d'] = spei30d_data['spei30d']
weather['spei90d'] = spei90d_data['spei90d']
weather['spei180d'] = spei180d_data['spei180d']
weather['pdsi'] = pdsi_data['pdsi']

## 2. Clean Dataset and Meta File

In [7]:
names

,Abbreviation,Full Name,Description
0,tmmx,Daily Maximum Air Temperature,Maximum air temperature at 2 meters above grou...
1,tmmn,Daily Minimum Air Temperature,Minimum air temperature at 2 meters above grou...
2,vpd,Vapor Pressure Deficit,Difference between saturation vapor pressure a...
3,rmax,Maximum Relative Humidity,Maximum daily relative humidity (%) at 2 meters
4,rmin,Minimum Relative Humidity,Minimum daily relative humidity (%) at 2 meters
5,sph,Specific Humidity,Mass of water vapor per unit mass of air (kg/kg)
6,pr,Precipitation,Daily total precipitation (mm)
7,vs,Wind Speed,Daily wind speed (m/s) at 10 meters
8,srad,Solar Radiation,Daily incoming shortwave radiation (W/m²)
9,etr,Actual Evapotranspiration,Estimated evapotranspiration from actual veget...
10,bi,Burning Index,"Fire danger index derived from temperature, hu..."
11,erc,Energy Release Component,Estimated energy release per unit area (MJ/m²)...
12,fm100,100-hour Dead Fuel Moisture,Moisture content of medium-size dead fuels (%)...
13,fm1000,1000-hour Dead Fuel Moisture,Moisture content of large dead fuels (%) affec...
14,spi30d,Standardized Precipitation Index 30-Day,Short-term precipitation deficit; captures rec...
15,spi180d,Standardized Precipitation Index 180-Day,Longer-term precipitation deficit; indicates p...
16,spei30d,Standardized Precipitation Evapotranspiration ...,Short-term combined precipitation and evapotra...
17,spei90d,Standardized Precipitation Evapotranspiration ...,Seasonal combined precipitation and evapotrans...
18,spei180d,Standardized Precipitation Evapotranspiration ...,Long-term combined precipitation and evapotran...
19,pdsi,Palmer Drought Severity Index,Long-term drought index combining temperature ...

In [8]:
# Create a units dictionary
units = {
    "tmmx": "°C",
    "tmmn": "°C",
    "vpd": "kPa",
    "rmax": "%",
    "rmin": "%",
    "sph": "kg/kg",
    "pr": "mm",
    "vs": "m/s",
    "srad": "W/m²",
    "etr": "mm",
    "bi": "index",
    "erc": "MJ/m²",
    "fm100": "%",
    "fm1000": "%",
    "spi30d": "index",
    "spi180d":"index",
    "spei30d":"index",
    "spei90d":"index",
    "spei180d":"index",
    "pdsi":"index"
}

# Map abbreviations to units
names["Units"] = names["Abbreviation"].map(units)

In [9]:
New_Names = dict(zip(names['Abbreviation'], names['Full Name'] ))

In [10]:
renamed = weather.rename(columns = New_Names)

In [11]:
renamed

,Sample_ID,Date,Burning Index,Energy Release Component,Actual Evapotranspiration,100-hour Dead Fuel Moisture,1000-hour Dead Fuel Moisture,Precipitation,Maximum Relative Humidity,Minimum Relative Humidity,...,Daily Minimum Air Temperature,Daily Maximum Air Temperature,Vapor Pressure Deficit,Wind Speed,Standardized Precipitation Index 30-Day,Standardized Precipitation Index 180-Day,Standardized Precipitation Evapotranspiration Index 30-Day,Standardized Precipitation Evapotranspiration Index 90-Day,Standardized Precipitation Evapotranspiration Index 180-Day,Palmer Drought Severity Index
0,1,2018-01-01,24.0,37.0,1.7,16.600000,13.700000,0.0,97.800003,52.700001,...,283.000000,290.700012,0.41,1.3,-2.09,-2.09,-2.09,-2.09,-2.09,-2.390000
1,1,2018-01-02,25.0,39.0,2.0,15.900000,13.800000,0.0,90.599998,43.200001,...,285.299988,294.399994,0.68,1.2,-2.09,-2.09,-2.09,-2.09,-2.09,-2.390000
2,1,2018-01-03,23.0,36.0,1.6,15.900000,13.800000,0.0,93.500000,53.400002,...,286.000000,292.899994,0.50,1.2,-1.69,-2.09,-2.09,-2.09,-2.09,-2.550000
3,1,2018-01-04,27.0,38.0,2.3,16.299999,14.100000,0.0,98.300003,47.700001,...,285.000000,294.200012,0.56,1.9,-1.69,-2.09,-2.09,-2.09,-2.09,-2.550000
4,1,2018-01-05,31.0,38.0,3.1,16.000000,14.200000,0.0,89.699997,46.299999,...,286.500000,294.600006,0.67,3.0,-1.69,-2.09,-2.09,-2.09,-2.09,-2.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446335,173,2025-01-19,23.0,28.0,1.7,12.600000,20.700001,0.0,76.199997,28.600000,...,262.899994,276.799988,0.31,2.7,1.01,0.90,0.90,0.90,0.63,1.219999
446336,173,2025-01-20,26.0,29.0,1.8,12.600000,20.200001,0.0,77.000000,26.700001,...,260.500000,275.200012,0.28,3.3,1.01,0.90,0.90,0.90,0.63,1.219999
446337,173,2025-01-21,27.0,32.0,2.4,11.300000,19.700001,0.0,53.599998,20.200001,...,265.500000,279.000000,0.45,3.0,1.01,0.90,0.90,0.90,0.63,1.219999
446338,173,2025-01-22,26.0,34.0,2.3,10.300000,19.299999,0.0,51.900002,18.799999,...,266.299988,280.399994,0.50,2.5,1.01,0.90,0.90,0.90,0.63,1.219999
446339,173,2025-01-23,30.0,37.0,3.1,9.100000,18.799999,0.0,39.799999,14.400000,...,268.500000,282.200012,0.62,3.0,0.63,0.90,0.39,0.71,0.63,1.240000

In [12]:
weather_names = names[['Full Name','Units','Description']]

In [13]:
weather_names

,Full Name,Units,Description
0,Daily Maximum Air Temperature,°C,Maximum air temperature at 2 meters above grou...
1,Daily Minimum Air Temperature,°C,Minimum air temperature at 2 meters above grou...
2,Vapor Pressure Deficit,kPa,Difference between saturation vapor pressure a...
3,Maximum Relative Humidity,%,Maximum daily relative humidity (%) at 2 meters
4,Minimum Relative Humidity,%,Minimum daily relative humidity (%) at 2 meters
5,Specific Humidity,kg/kg,Mass of water vapor per unit mass of air (kg/kg)
6,Precipitation,mm,Daily total precipitation (mm)
7,Wind Speed,m/s,Daily wind speed (m/s) at 10 meters
8,Solar Radiation,W/m²,Daily incoming shortwave radiation (W/m²)
9,Actual Evapotranspiration,mm,Estimated evapotranspiration from actual veget...
10,Burning Index,index,"Fire danger index derived from temperature, hu..."
11,Energy Release Component,MJ/m²,Estimated energy release per unit area (MJ/m²)...
12,100-hour Dead Fuel Moisture,%,Moisture content of medium-size dead fuels (%)...
13,1000-hour Dead Fuel Moisture,%,Moisture content of large dead fuels (%) affec...
14,Standardized Precipitation Index 30-Day,index,Short-term precipitation deficit; captures rec...
15,Standardized Precipitation Index 180-Day,index,Longer-term precipitation deficit; indicates p...
16,Standardized Precipitation Evapotranspiration ...,index,Short-term combined precipitation and evapotra...
17,Standardized Precipitation Evapotranspiration ...,index,Seasonal combined precipitation and evapotrans...
18,Standardized Precipitation Evapotranspiration ...,index,Long-term combined precipitation and evapotran...
19,Palmer Drought Severity Index,index,Long-term drought index combining temperature ...

## 3. Export Files

In [14]:
renamed.to_csv('../data/raw/gridmet_final.csv',index=False)
weather_names.to_csv('../data/raw/weather_meta.csv',index=False)